accounts:
  - name: yazhini
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
validator:
  name: yazhini
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
  
build:
  binary: "calibd"  
  ldflags: [ "-X main.Version=development", "-X main.Date=08/02/2022T19:54" ]

